services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://authuser:authpass@db/authdb
      SECRET_KEY: dcdhcbuycewuchecieherirhifhruihcuidcjdch
      REFRESH_SECRET_KEY: ecneuniunuivnfuivnfuivhuvuhuhohivheuhv
      GITHUB_CLIENT_ID: your_new_client_id
      GITHUB_CLIENT_SECRET: your_new_client_secret
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
